version: '3.9'

services:
  frontend:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    command: npm run dev

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
