apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::151972243519:user/eks_terraform
      username: eks_terraform
      groups:
        - system:masters
